version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: tail -f /etc/hosts
    volumes:
      - ./:/src:rw
    links:
      - redis
    ports:
      - "8080:8080"
      - "7777:7777"

  redis:
    image: redis:latest
    expose:
      - "6379"
