version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: tail -f /etc/hosts
    volumes:
      - ./:/src:rw
    ports:
      - "8080:8080"
      - "80:7777"
